# Generated by Django 2.2.28 on 2022-09-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaccount',
            old_name='extra_data',
            new_name='extra_data_old',
        ),
        migrations.RenameField(
            model_name='socialapp',
            old_name='client_id',
            new_name='client_id_old',
        ),
        migrations.RenameField(
            model_name='socialapp',
            old_name='key',
            new_name='key_old',
        ),
        migrations.RenameField(
            model_name='socialapp',
            old_name='secret',
            new_name='secret_old',
        ),
        migrations.RenameField(
            model_name='socialtoken',
            old_name='token',
            new_name='token_old',
        ),
        migrations.RenameField(
            model_name='socialtoken',
            old_name='token_secret',
            new_name='token_secret_old',
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set(),
        ),
    ]
