# Generated by Django 2.2.28 on 2022-09-12 19:10

import allauth.socialaccount.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20220912_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='extra_data_old',
            field=allauth.socialaccount.fields.JSONField(default=dict, verbose_name='extra data (old)'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='client_id_old',
            field=models.CharField(help_text='App ID, or consumer key', max_length=191, verbose_name='client id (old)'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='key_old',
            field=models.CharField(blank=True, help_text='Key', max_length=191, verbose_name='key (old)'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='secret_old',
            field=models.CharField(blank=True, help_text='API secret, client secret, or consumer secret', max_length=191, verbose_name='secret key (old)'),
        ),
        migrations.AlterField(
            model_name='socialtoken',
            name='token_old',
            field=models.TextField(help_text='"oauth_token" (OAuth1) or access token (OAuth2)', verbose_name='token (old)'),
        ),
        migrations.AlterField(
            model_name='socialtoken',
            name='token_secret_old',
            field=models.TextField(blank=True, help_text='"oauth_token_secret" (OAuth1) or refresh token (OAuth2)', verbose_name='token secret (old)'),
        ),
    ]
