# Generated by Django 2.2.28 on 2022-09-12 19:11

import allauth.socialaccount.fields
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0005_auto_20220912_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='extra_data',
            field=django_cryptography.fields.encrypt(allauth.socialaccount.fields.JSONWrappedTextField(default=dict, null=True, blank=True, verbose_name='extra data')),
        ),
        migrations.AddField(
            model_name='socialapp',
            name='client_id',
            field=django_cryptography.fields.encrypt(models.CharField(default='', help_text='App ID, or consumer key', max_length=191, verbose_name='client id')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialapp',
            name='key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Key', max_length=191, verbose_name='key')),
        ),
        migrations.AddField(
            model_name='socialapp',
            name='secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='API secret, client secret, or consumer secret', max_length=191, verbose_name='secret key')),
        ),
        migrations.AddField(
            model_name='socialtoken',
            name='token',
            field=django_cryptography.fields.encrypt(models.TextField(default='', help_text='"oauth_token" (OAuth1) or access token (OAuth2)', verbose_name='token')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialtoken',
            name='token_secret',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='"oauth_token_secret" (OAuth1) or refresh token (OAuth2)', verbose_name='token secret')),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'uid')},
        ),
    ]
