# Generated by Django 2.2.28 on 2022-09-12 19:11

from django.db import migrations

import json


def forwards_encrypted_char(apps, schema_editor):
    SocialApp = apps.get_model("socialaccount", "SocialApp")
    SocialAccount = apps.get_model("socialaccount", "SocialAccount")
    SocialToken = apps.get_model("socialaccount", "SocialToken")

    for row in SocialApp.objects.all():
        row.client_id = row.client_id_old
        row.secret = row.secret_old
        row.key = row.key_old
        row.save(update_fields=["client_id", "secret", "key"])

    for row in SocialAccount.objects.all():
        if isinstance(row.extra_data_old, dict):
            row.extra_data = json.dumps(row.extra_data_old)
        else:
            row.extra_data = row.extra_data_old
        row.save(update_fields=["extra_data"])

    for row in SocialToken.objects.all():
        row.token = row.token_old
        row.token_secret = row.token_secret_old
        row.save(update_fields=["token", "token_secret"])


def reverse_encrypted_char(apps, schema_editor):
    SocialApp = apps.get_model("socialaccount", "SocialApp")
    SocialAccount = apps.get_model("socialaccount", "SocialAccount")
    SocialToken = apps.get_model("socialaccount", "SocialToken")

    for row in SocialApp.objects.all():
        row.client_id_old = row.client_id
        row.secret_old = row.secret
        row.key_old = row.key
        row.save(update_fields=["client_id_old", "secret_old", "key_old"])

    for row in SocialAccount.objects.all():
        row.extra_data_old = row.extra_data
        row.save(update_fields=["extra_data_old"])

    for row in SocialToken.objects.all():
        row.token_old = row.token
        row.token_secret_old = row.token_secret
        row.save(update_fields=["token_old", "token_secret_old"])


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0006_auto_20220912_1911'),
    ]

    operations = [
        migrations.RunPython(forwards_encrypted_char, reverse_encrypted_char),
    ]
