# Generated by Django 2.2.28 on 2022-09-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0007_auto_20220912_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='extra_data_old',
        ),
        migrations.RemoveField(
            model_name='socialapp',
            name='client_id_old',
        ),
        migrations.RemoveField(
            model_name='socialapp',
            name='key_old',
        ),
        migrations.RemoveField(
            model_name='socialapp',
            name='secret_old',
        ),
        migrations.RemoveField(
            model_name='socialtoken',
            name='token_old',
        ),
        migrations.RemoveField(
            model_name='socialtoken',
            name='token_secret_old',
        ),
    ]
